spring.application.name=ticketflow-api

spring.datasource.url=jdbc:postgresql://localhost:5432/ticketflow_db
spring.datasource.username=ticketflow_user
spring.datasource.password=ticketflow123

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

jwt.secret=TicketFlowSecretKeyForJwtGenerationMustBeAtLeast32CharactersLong
jwt.expiration-in-seconds=3600
